### ISSUE TITLE
PHP CS bug

### ISSUE THREAD

**Issue by LanceJernigan** [thinkpyxl/outset#32]
`npm run build` fails because of php coding standards on a fresh build.  This needs to use a project package, not a global package.

Adding `"squizlabs/php_codesniffer": "3.*"` to `composer.json` doesn't resolve the issue

**Comment by mizner** [comment]
Add to workspace
```
"phpcs.standard": "./phpcs.xml",
```

Note, this concerns me about other settings

**Comment by Pyxl-Jim** [comment]
Fixed by removing php from `prod`, and separating out `phpcs` and `phpcbf` into separate tasks in `build`.
